id: P010713
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:21:07.769003
source_metadata:
  id: bdr:W1KG25219
  title: རྗེ་བཙུན་གྲགས་པ་མཁས་གྲུབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཐར་འདོད་སྙིང་གི་དགའ་སྟོན།
  author: ''
  volumes:
    af38c2586cbf4617bf91c1fe06563899:
      image_group_id: I1KG25221
      title: ''
      volume_number: 1
      total_pages: 240
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
