id: P010713
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25219
  title: རྗེ་བཙུན་གྲགས་པ་མཁས་གྲུབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཐར་འདོད་སྙིང་གི་དགའ་སྟོན།
  author: ''
  volumes:
    af38c2586cbf4617bf91c1fe06563899:
      image_group_id: I1KG25221
      title: ''
      volume_number: 1
      total_pages: 240
