id: I7C09C8B2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T14:46:52+00:00'
last_modified: '2022-06-08T16:59:40.785503+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25219
  title: རྗེ་བཙུན་གྲགས་པ་མཁས་གྲུབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཐར་འདོད་སྙིང་གི་དགའ་སྟོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    CE26:
      image_group_id: I1KG25221
      title: ''
      total_pages: 240
      order: 1
      base_file: CE26.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
